# Generated by Django 2.0.7 on 2018-07-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='short_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
